name: Continuous Integration Tests

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build Docker container
        run: make dev-start
      - name: Run tests
        run: make test